name: Release

on:
  pull_request:
    types: ["closed"]
  issue_comment:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "pr-release"
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Create release
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease_id: "rc"
          update_major_tag: true
