name: Run tests

on:
  push:

env:
  NODE_OPTIONS: "--experimental-vm-modules npx jest"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with: 
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npm test
